"""Bundle the split Cargo config schema into a single file.

Reads cargo-config.schema.json (root), follows cross-file $refs to sibling
*.schema.json files, and emits cargo-config.json with every $ref
rewritten to an internal #/$defs/<name> reference. The bundle is what tombi
and other validators that do not follow cross-file $refs should consume.

Run from this directory:
    uv run cargo-schema-bundle
"""

import argparse
import json
import subprocess
from collections import OrderedDict
from copy import deepcopy
from pathlib import Path
from typing import TypeAlias, cast

JsonValue: TypeAlias = (
    "str | int | float | bool | None | list[JsonValue] | OrderedDict[str, JsonValue]"
)
JsonDict: TypeAlias = "OrderedDict[str, JsonValue]"

REPO: Path = Path.cwd()
ROOT_FILE: Path = REPO / "schemas" / "cargo-config.schema.json"
COMMON_FILE: Path = REPO / "schemas" / "common.schema.json"
OUTPUT_FILE: Path = REPO / "cargo-config.json"

# Map root.properties.<key> -> ($defs key for the inlined subschema).
# Wrappers ([profile.*], [registries.*], [source.*], [target.*]) get plural
# names so the inner per-entry def can keep the singular name.
SECTION_DEF_NAME: dict[str, str] = {
    "alias": "alias",
    "build": "build",
    "cache": "cache",
    "cargo-new": "cargoNew",
    "credential-alias": "credentialAlias",
    "doc": "doc",
    "env": "env",
    "future-incompat-report": "futureIncompatReport",
    "http": "http",
    "install": "install",
    "net": "net",
    "patch": "patch",
    "profile": "profiles",
    "registries": "registries",
    "registry": "registry",
    "resolver": "resolver",
    "source": "sources",
    "target": "targets",
    "term": "term",
}

STRIP_TOP_LEVEL_KEYS: set[str] = {"$schema", "$id"}


def load(path: Path) -> JsonDict:
    with path.open("r", encoding="utf-8") as fh:
        data = cast(object, json.load(fh, object_pairs_hook=OrderedDict))
    if not isinstance(data, OrderedDict):
        raise SystemExit(f"{path}: expected a JSON object at the root")
    return cast("JsonDict", data)


def expect_dict(value: JsonValue, label: str) -> JsonDict:
    if not isinstance(value, OrderedDict):
        raise SystemExit(f"{label}: expected an object, got {type(value).__name__}")
    return cast("JsonDict", value)


def rewrite_refs(node: JsonValue) -> None:
    """Rewrite all $refs in `node` so they target #/$defs/<name>.

    - "common.schema.json#/$defs/X"  -> "#/$defs/X"
    - "#/$defs/X"                    -> unchanged
    - bare "<file>.schema.json"      -> caller handles (top-level only)
    """
    if isinstance(node, OrderedDict):
        dict_node = cast("JsonDict", node)
        ref = dict_node.get("$ref")
        if isinstance(ref, str) and ".schema.json" in ref:
            filename, _, fragment = ref.partition("#")
            if filename == "common.schema.json" or fragment.startswith("/$defs/"):
                dict_node["$ref"] = "#" + fragment
            elif filename.endswith(".schema.json"):
                section = filename.removesuffix(".schema.json")
                if section not in SECTION_DEF_NAME:
                    raise SystemExit(f"unknown schema reference: {ref}")
                dict_node["$ref"] = f"#/$defs/{SECTION_DEF_NAME[section]}"
        for v in dict_node.values():
            rewrite_refs(v)
    elif isinstance(node, list):
        for item in cast("list[JsonValue]", node):
            rewrite_refs(item)


def merge_defs(target: JsonDict, source: JsonDict, source_name: str) -> None:
    """Merge `source` $defs into `target` $defs. Error on collision."""
    for key, value in source.items():
        if key in target and target[key] != value:
            raise SystemExit(
                f"$defs collision while bundling {source_name}: '{key}' already exists with different content"
            )
        target[key] = value


def get_dict(parent: JsonDict, key: str) -> JsonDict:
    """Return parent[key] as a JsonDict, or an empty one if missing."""
    value = parent.get(key)
    if value is None:
        return cast("JsonDict", OrderedDict())
    return expect_dict(value, f"{key}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT_FILE)
    output = parser.parse_args().output
    root = load(ROOT_FILE)
    common = load(COMMON_FILE)

    bundle: JsonDict = cast("JsonDict", OrderedDict())
    bundle["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    bundle["$id"] = (
        "https://raw.githubusercontent.com/kjanat/cargo-config-schema/"
        "master/cargo-config.json"
    )
    bundle["title"] = root.get("title", "cargo configuration")
    bundle["description"] = (
        "Bundled Cargo configuration schema (auto-generated by cargo-schema-bundle from"
        " cargo-config.schema.json + sibling section schemas). Edit the split"
        " files, then re-run cargo-schema-bundle.\n"
        "https://doc.rust-lang.org/cargo/reference/config.html"
    )
    bundle["type"] = root.get("type", "object")
    for key in (
        "$comment",
        "required",
        "additionalProperties",
        "allOf",
        "anyOf",
        "oneOf",
        "not",
        "dependentRequired",
    ):
        if key in root:
            bundle[key] = deepcopy(root[key])
    # Carry over any vendor extension keys (x-tombi-*, x-taplo, x-intellij-*) from root.
    for ext_key, ext_value in root.items():
        if ext_key.startswith("x-"):
            bundle[ext_key] = deepcopy(ext_value)
    examples = root.get("examples")
    if examples is not None:
        bundle["examples"] = deepcopy(examples)

    # Carry over root-level properties that are not section refs (paths, include).
    bundle_properties: JsonDict = cast("JsonDict", OrderedDict())
    root_properties = get_dict(root, "properties")
    for key, value in root_properties.items():
        if key in SECTION_DEF_NAME:
            def_name = SECTION_DEF_NAME[key]
            bundle_properties[key] = cast(
                "JsonDict",
                OrderedDict([("$ref", f"#/$defs/{def_name}")]),
            )
        else:
            bundle_properties[key] = deepcopy(value)
    bundle["properties"] = bundle_properties

    # Build $defs: start with root's own $defs (e.g. includeEntry), then common.
    bundle_defs: JsonDict = cast("JsonDict", OrderedDict())
    for key, value in get_dict(root, "$defs").items():
        bundle_defs[key] = deepcopy(value)
    merge_defs(bundle_defs, get_dict(common, "$defs"), "common.schema.json")

    # For each section, inline its split file as $defs[<def_name>] and hoist its
    # internal $defs into root $defs so internal #/$defs/* refs keep resolving.
    for section, def_name in SECTION_DEF_NAME.items():
        section_file = ROOT_FILE.parent / f"{section}.schema.json"
        if not section_file.exists():
            raise SystemExit(f"missing split file: {section_file}")
        section_schema = load(section_file)

        inner_defs = get_dict(section_schema, "$defs")
        _ = section_schema.pop("$defs", None)
        for strip_key in STRIP_TOP_LEVEL_KEYS:
            _ = section_schema.pop(strip_key, None)

        rewrite_refs(section_schema)
        for inner_key in inner_defs:
            rewrite_refs(inner_defs[inner_key])

        if def_name in bundle_defs and bundle_defs[def_name] != section_schema:
            raise SystemExit(
                f"$defs collision: section '{section}' wants def name '{def_name}' but it is already taken"
            )
        bundle_defs[def_name] = section_schema
        merge_defs(bundle_defs, inner_defs, section_file.name)

    bundle["$defs"] = bundle_defs
    rewrite_refs(bundle)

    formatted = subprocess.run(
        [
            "dprint",
            "fmt",
            "--config",
            str(REPO / ".dprint.jsonc"),
            "--stdin",
            "cargo-config.json",
        ],
        input=json.dumps(bundle, ensure_ascii=False),
        capture_output=True,
        encoding="utf-8",
        check=True,
    )
    _ = output.write_text(formatted.stdout, encoding="utf-8", newline="\n")
    print(f"wrote {output} ({output.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
